# Generated by Django 2.2.14 on 2022-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_default',
            name='unique',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='api_default',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
