# Generated by Django 2.2.14 on 2022-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_auto_20220814_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_default',
            name='Email',
            field=models.EmailField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='api_default',
            name='Firstname',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='api_default',
            name='Lastname',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
